apiVersion: v1
kind: Secret
metadata:
  name: duyi-service-secret
  labels:
    app: duyi-service
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  WEB_JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey | b64enc | quote }}
