"""del product brand

Revision ID: 631b138f29be
Revises: a4d7d612e512
Create Date: 2026-08-25 15:53:44.804034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631b138f29be'
down_revision: Union[str, Sequence[str], None] = 'a4d7d612e512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
